### PR TITLE
Feature: Access fields using dcm.field instead of dcm[tag"field"]

### PR DESCRIPTION
**Pull request by notZaki**
The current fieldnames are strings because they use the `name` defined in the [DICOM registry](http://dicom.nema.org/dicom/2013/output/chtml/part06/chapter_6.html). These names contains spaces.

This PR changes the fieldnames into symbols by using the `keyword` defined in the same DICOM registry---these do not have spaces. 

To avoid breaking existing code, fieldnames are still accepted as strings. These are converted to symbols by stripping any spaces. There are a few corner cases where this can fail, e.g. some names contain a parenthesis that is omitted in the keyword.

The main advantage of this change is that it will allow us to use dot syntax in the future, e.g. `dcm.PixelData` instead of `dcm[(0x7FE0,0x0010)]` or `dcm[tag"Pixel Data"]`.

### CODE REVIEW

**Comment by notZaki** [comment]
Update: The current `dcm_parse` function returns a dictionary. The PR has added a new type called `DICOMData` which wraps the dictionary. This allows new ways of accessing the dicom data because `getindex` and `getproperty` can dispatch off the type.

With these changes, the dicom data can be accessed by `dcm.fieldname` or `dcm[:fieldname]` or `dcm["fieldname"]`. 
The previous approaches still continue to work, i.e. `dcm[(0xHEX,0xHEX)]` and `dcm[tag"fieldname"]` remain valid.

**Comment by Tokazama** [comment]
Looks good! Would it make sense to use an immutable dict for the package's look up table?

**Comment by notZaki** [comment]
I didn't know they were a thing. I'll give it a try.

**Comment by notZaki** [comment]
I tried using an immutable dict for `dcm_dict` and `fieldname_dict` along with combinations where one was immutable and the other wasn't. In each case, the ImmutableDict was slower. 

According to the [julia docs](https://docs.julialang.org/en/v1/base/collections/#Base.ImmutableDict):
> [ImmutableDict] is optimal for small dictionaries that are constructed over many individual insertions.

which might explain why the look up table doesn't benefit; it is a large table that is constructed once.

**Pull request merged**
