### PR TITLE
Remove Julia 1.3 from Travis CI configuration

### PR DESCRIPTION
**Pull request by notZaki**
Julia 1.3 doesn't need to be in the tests. 
It was added when Julia 1.3 was the latest version and I didn't know that the version `'1'` would always use the latest release.

### CODE REVIEW

**Comment by notZaki** [comment]
A more aggressive approach could be to remove the latest release, i.e. `'1'`, from the tests as well. In theory, the builds on 1.0 and nightly should encompass everything in between.

**Comment by DilumAluthge** [comment]
> A more aggressive approach could be to remove the latest release, i.e. `'1'`, from the tests as well. In theory, the builds on 1.0 and nightly should encompass everything in between.

In theory.... sometimes nightly does weird stuff though.

**Comment by DilumAluthge** [comment]
One thing we could consider would be switching from Travis to GitHub Actions. Usually GH Actions is much faster.

If you're interested, let me know - I'm happy to make a PR to set up GH Actions for CI testing on this repo.

**Comment by notZaki** [comment]
That sounds great! 
I'm curious about GH Actions too, so seeing it applied in a setup I'm previously familiar with would be a useful learning opportunity for me.

**Pull request merged**
