### PR TITLE
Pass aux_vr to SQ elements in dcm_write

### PR DESCRIPTION
**Pull request by AaronGhost**
- Ensure that auxilliary VR provided by the user is passed when writing all tags including the ones in sequences. This can be used to write private tags and provide VR when multiple are possible (See #87).

- Deactivate tests for non-available file (`DX_Implicit_Little_Interleaved`)
- Add a test where the VR type of a tag within a sequence is changed when written.

### CODE REVIEW

**Comment by notZaki** [comment]
Thanks for working on this (and for identifying the original issue)!

It's been a while since this package was updated, so I'll try to see if the test data can be fixed.

**Comment by AaronGhost** [comment]
I think I might have some more issues with the `dcm_write` function, do you prefer me to add them into my original issue or would you prefer I open extra issues for it?

**Comment by notZaki** [comment]
Either works.

**Comment by AaronGhost** [comment]
I added some fixes for the two last issues. The only one I am not entirely sure how to deal with is the tags with multiple possible VR:
- The VR from the data could be parsed as a lower-level aux_vr
- The VR could be determined from the standard requirement
- The VR could just be picked as the first few characters
- Something else???

Let me know what you think is best

**Comment by notZaki** [comment]
Thanks! 
I opened a PR for your branch that should fix the tests on nightly.

The multi-VR problem is tricky. Ideally, we should use the standard to figure out the appropriate VR, but that's also the most amount of work to resolve everything on a case by case basis. For example, `:RealWorldValueLastValueMapped` should have it's VR determined by `:PixelRepresentation` (0028,0103).
I remember trying to work on something similar, but ran into some edge cases where the VR depends on a value that occurs later in the file, e.g. imagine if VR for (0028, xxxx) depended on (0030, xxxx), and so gave up for my own sanity. Maybe I overlooked something, or maybe the newer standard is better. 

I suppose the first step is to update dcm_dict and get an idea of how many multi-VR fields there are. I think I have a script for that somewhere. I'll try to find it.

**Pull request merged**
